name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv.
          version: "0.7.8"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        # For example, using `pytest`
        run: uv run pytest tests

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       packages: write
#     steps:
#       - uses: actions/checkout@v4
#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: '3.12'
#       - name: Install uv
#         run: |
#           curl -LsSf https://astral.sh/uv/install.sh | sh
#           echo "$HOME/.local/bin" >> $GITHUB_PATH
#       - name: Install dependencies
#         run: uv sync
#       - name: Build Docker image
#         run: docker build -t ghcr.io/${{ github.repository }}:${{ github.sha }} .
#       - name: Log in to GHCR
#         uses: docker/login-action@v3
#         with:
#           registry: ghcr.io
#           username: ${{ github.actor }}
#           password: ${{ secrets.GITHUB_TOKEN }}
#       - name: Push image
#         run: docker push ghcr.io/${{ github.repository }}:${{ github.sha }}

